services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flashcards_php
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - flashcards_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: flashcards_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: flashcards
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - flashcards_network

volumes:
  db_data:

networks:
  flashcards_network:
    driver: bridge